// Wordlist consists of 181 most populous countries listed in a randomized order
// NOTE: Wordlist and game doesn't consider England or other British Isles seperately from UK to prevent confusion,
// but the data DOES consider them seperately

const wordlist = [
  'Haiti',
  'Netherlands',
  'Suriname',
  'Mauritius',
  'Brazil',
  'Switzerland',
  'Rwanda',
  'Mongolia',
  'Austria',
  'Guyana',
  'Kyrgyzstan',
  'Australia',
  'Armenia',
  'New Zealand',
  'Lebanon',
  'Oman',
  'Algeria',
  'Germany',
  'Cambodia',
  'Spain',
  'Central African Republic',
  'Denmark',
  'Latvia',
  'Niger',
  'Cape Verde',
  'Luxembourg',
  'Nicaragua',
  'El Salvador',
  'Federated States of Micronesia',
  'North Macedonia',
  'Iceland',
  'Cook Islands',
  'Slovakia',
  'Bahrain',
  'Malta',
  'Sweden',
  'Equatorial Guinea',
  'United Kingdom',
  'Monaco',
  'Belarus',
  'Mauritania',
  'Mali',
  'Solomon Islands',
  'Lithuania',
  'Nigeria',
  'Saint Vincent and the Grenadines',
  'Ivory Coast',
  'Morocco',
  'Greece',
  'New Caledonia',
  'Zambia',
  'Kuwait',
  'Uruguay',
  'Guinea',
  'Bangladesh',
  'Kenya',
  'Liechtenstein',
  'Samoa',
  'Iraq',
  'Chile',
  'Nauru',
  'Togo',
  'Vanuatu',
  'Guatemala',
  'Singapore',
  'Comoros',
  'Kiribati',
  'Venezuela',
  'Laos',
  'Japan',
  'Sierra Leone',
  'South Africa',
  'Guam',
  'Cuba',
  'Fiji',
  'Bhutan',
  'Syria',
  'Burkina Faso',
  'Philippines',
  'Andorra',
  'Ireland',
  'Gambia',
  'Afghanistan',
  'Israel',
  'Saudi Arabia',
  'Brunei',
  'Turkmenistan',
  'Iran',
  'Thailand',
  'Sao Tome and Principe',
  'Barbados',
  'France',
  'Argentina',
  'Benin',
  'Jordan',
  'Serbia',
  'Ghana',
  'Albania',
  'Zimbabwe',
  'Costa Rica',
  'South Sudan',
  'Angola',
  'Uzbekistan',
  'Romania',
  'Tanzania',
  'Gabon',
  'Slovenia',
  'Hungary',
  'Vietnam',
  'Tajikistan',
  'Bahamas',
  'Cameroon',
  'Türkiye',
  'Belgium',
  'Libya',
  'Estonia',
  'Ethiopia',
  'French Polynesia',
  'Djibouti',
  'Sudan',
  'Malawi',
  'Saint Lucia',
  'Botswana',
  'Hong Kong',
  'Tunisia',
  'Mexico',
  'Peru',
  'Papua New Guinea',
  'Guinea-Bissau',
  'Chad',
  'Ecuador',
  'Belize',
  'Canada',
  'Jamaica',
  'Moldova',
  'Finland',
  'Kazakhstan',
  'Bolivia',
  'Qatar',
  'The Democratic Republic of Congo',
  'Poland',
  'Croatia',
  'Bulgaria',
  'Namibia',
  'Palestine',
  'Congo',
  'Panama',
  'Myanmar',
  'Cyprus',
  'Liberia',
  'United Arab Emirates',
  'Czech Republic',
  'China',
  'India',
  'Eritrea',
  'Italy',
  'Pakistan',
  'Grenada',
  'United States',
  'North Korea',
  'Azerbaijan',
  'Georgia',
  'Dominican Republic',
  'Uganda',
  'Portugal',
  'Madagascar',
  'Honduras',
  'Maldives',
  'Russia',
  'Burundi',
  'Eswatini',
  'Egypt',
  'Nepal',
  'Senegal',
  'Mozambique',
  'Yemen',
  'Ukraine',
  'Somalia',
  'Trinidad and Tobago',
  'Paraguay',
  'Lesotho',
  'Taiwan',
  'Bosnia and Herzegovina',
  'South Korea',
  'Sri Lanka',
  'Colombia',
  'Malaysia',
  'Norway',
  'Indonesia',
  'Montenegro',
];

export default wordlist;
