// Wordlist consists of 100 most populous countries listed in a randomized order
// NOTE: Wordlist and game doesn't consider England seperately from UK to prevent confusion,
// but the data DOES consider them seperately

const wordlist = [
  'The Democratic Republic of Congo',
  'Russian Federation',
  'Venezuela',
  'Haiti',
  'Zimbabwe',
  'Portugal',
  'Switzerland',
  'China',
  'Honduras',
  'United Kingdom',
  'United Arab Emirates',
  'Israel',
  'Thailand',
  'Ivory Coast',
  'Germany',
  'Benin',
  'Senegal',
  'Canada',
  'Italy',
  'South Africa',
  'Iran',
  'Kazakhstan',
  'Turkey',
  'Burundi',
  'Sri Lanka',
  'Papua New Guinea',
  'Tanzania',
  'Rwanda',
  'Somalia',
  'Tajikistan',
  'Sweden',
  'Egypt',
  'India',
  'Niger',
  'Spain',
  'Cuba',
  'Malawi',
  'Zambia',
  'Ghana',
  'Kenya',
  'Austria',
  'Uzbekistan',
  'Bangladesh',
  'Ecuador',
  'North Korea',
  'Peru',
  'Pakistan',
  'Australia',
  'Morocco',
  'Angola',
  'Colombia',
  'Greece',
  'Afghanistan',
  'Jordan',
  'Burkina Faso',
  'Ukraine',
  'Guinea',
  'Saudi Arabia',
  'Romania',
  'South Sudan',
  'Japan',
  'Netherlands',
  'Bolivia',
  'Mozambique',
  'Vietnam',
  'Chad',
  'Chile',
  'South Korea',
  'Indonesia',
  'Brazil',
  'Philippines',
  'Cambodia',
  'Azerbaijan',
  'Belarus',
  'Belgium',
  'Tunisia',
  'Hungary',
  'Mexico',
  'Uganda',
  'Nepal',
  'Czech Republic',
  'Iraq',
  'Dominican Republic',
  'Syria',
  'Nigeria',
  'Argentina',
  'Myanmar',
  'Algeria',
  'Madagascar',
  'Ethiopia',
  'Yemen',
  'Guatemala',
  'Poland',
  'United States',
  'Mali',
  'France',
  'Cameroon',
  'Malaysia',
  'Sudan',
];

export default wordlist;
